### ISSUE TITLE
Add supported procedure to connect to FujiNet device

### ISSUE THREAD

**Issue by eahumada** [atari800/atari800#127]
Add support procedure to connect a real FujiNet device via SIO2USB cable.

https://fujinet.online/

**Comment by mikrosk** [comment]
I'm sorry but what's the idea here? Fujinet is a Atari device, that way you could ask to support basically any Atari peripheral via SIO2USB... more sense would make to emulate (some of) its features in software.

**Comment by eahumada** [comment]
Yes, you are right, could be great to emulate some of the features (to play online for example with FujiNet users or open files over the network using the same software and protocols that FujiNet from the emulator). I wonder if require some extra work to connect from the atari800 emulator to Fujinet, or simple connect it via SIO2USB will work.

Also, I get some answers here: https://atariage.com/forums/topic/316678-connect-atari800-emulator-on-pc-to-sio-fujinet-device/

**Comment by eahumada** [comment]
Is the access to the emulated R: device enabled by default? How can be enabled?

**Comment by mikrosk** [comment]
> simple connect it via SIO2USB will work

No it wont but it shouldn't be that much work either.

> Is the access to the emulated R: device enabled by default

Yes, at least in the newer versions (Linux/Win32 only).

**Comment by mikrosk** [comment]
Out of curiosity I have taken a deeper look on R: -- there are basically two ways how the FujiNet integration could work:

- via the host serial port (supported only on Unix/Linux), i.e. `Atari800` would open `/dev/ttyS0` which would be the SIO2USB cable and setup a few basic things to make the FujiNet boot (i.e. send data back to the host and interpret them in `Atari800`)
- via R: IP emulation, i.e. R: would emulate whole FujiNet functionality in software and you'd run just Atari 8-bit software in the emulator

The former looks to me way easier. I personally do have a FujiNet adaptor + SIO2USB but right now they are in storage and to be honest, its usage in an emulator is not exactly on top of my Atari TODO list.

**Comment by mozzwald** [comment]
There has been some success at porting the FujiNet code to PC ([more info here](https://atariage.com/forums/topic/313544-fujinet-on-pc/) and the [ported code here](https://github.com/FujiNetWIFI/fujinet-pc)). This may be useful for adding something to atari800. I'm not familiar with atari800 myself, just sharing what I know.

Another option would be to connect a real FujiNet device to the host machine running the emulator, but I'm not sure that all the SIO pins are emulated. FujiNet requires *all* of the SIO pins.

**Comment by mozzwald** [comment]
FujiNet-PC has matured since I last posted here so I figured I would update with some more info.

fujinet-pc uses a custom `netsio` protocol which communicates over UDP and can be used by emulators to send/receive Atari SIO data. This protocol is currently being used with the Altirra emulator via the `fujinet-emulator-bridge`. The protocol is documented in the bridge repo at https://github.com/FujiNetWIFI/fujinet-emulator-bridge/blob/main/netsio.md. 

From what I can tell of the atari800 emulator (please correct me if I am wrong), the INTERRUPT and PROCEED SIO lines are not used anywhere. These are required for the FujiNet network device to function. FujiNet uses these to notify the Atari when more data is available from the network to read.

I have been thinking about how to implement this in atari800 and my first thought is to have a fujinet mode (command line option?) that pipes all SIO traffic through netsio to fujinet-pc and disables all atari800 SIO devices. Fujinet emulates most of the devices that atari800 does so it could be easier to just use one or the other.

**Comment by mikrosk** [comment]
Discussed already in #226, TL;DR: patches are welcome but we certainly don't have capacity to do this on our own. :(
