### ISSUE TITLE
In-scanline colour register update timing seems off since Ver 2.0.0

### ISSUE THREAD

**Issue by drpeterbatesuk** [atari800/atari800#163]
On real hardware there is a short delay between the completion of a write to a hardware colour register and that change taking effect on-screen.

This delay seems to have lengthened by 2 colour clocks in the update from Ver 1.3.6 to 2.0.0, when the exact cycle count code for CPU, ANTIC and GTIA was revised. Either that, or the synchronisation of CPU to screen has moved forward by 2 colour clocks.

Real hardware and Altirra have a shorter delay- that seen in 1.3.6, which seems to have been correct.

This is demonstrated by the following raster kernel executable produced by RastaConverter (GravityWormDuneWorm.xex) In Atari800, the discrepency is manifest by a small black artefactual square in the lower centre of the screen, not present on real hardware or Altirra.  This derives from a time-critical write to COLPM2 just before these pixels are displayed.  Editing the executable (output_1.xex) to make the effective point of colour change more obvious indicates that it occurs 2 colour clocks later in Atari800 than in Altirra or on real hardware.

[Downloads.zip](https://github.com/atari800/atari800/files/8903852/Downloads.zip)

**Comment by mikrosk** [comment]
This took a while to untangle. The root cause for this change is an innocently-looking commit 9668cd53. There's a [very hard to spot change](https://github.com/atari800/atari800/commit/9668cd530d31091a9c899b461598a94db023928b#diff-3867b069eb4bd5871ef96a2d30b6a78ae756a58bee84421611f7dec428a7b6b3L555) among the whiteline changes which has changed the behaviour as you describe it. 

When I reverted this ancient change, i.e. changed `GTIA_PRIOR` to `GTIA_OFFSET_PRIOR` at https://github.com/atari800/atari800/blob/70ab6aba601ce64bbed02bab99a5d824d0da2cbf/src/gtia.c#L603-L607
it produced a picture without the glitch:
![workaround](https://github.com/atari800/atari800/assets/3062260/419a0fc2-d2a2-4f91-879e-a42c719fc88e)

However there's a catch. This revert is basically wrong, it just happens to fix your problem because the other function is called. Look at their definitions: https://github.com/atari800/atari800/blob/70ab6aba601ce64bbed02bab99a5d824d0da2cbf/src/antic.c#L3201-L3222

you can spot the answer: with my revert `ANTIC_UpdateScanline` is called instead of `ANTIC_UpdateScanlinePrior`, therefore adding a couple of cycles more to `ANTIC_cur_screen_pos`.

That's as far as I can go with my knowledge, maybe @pfusik still remembers something? ;)

**Comment by pfusik** [comment]
This definitely should be `GTIA_OFFSET_PRIOR`. I removed the underscore accidentally.

> This revert is basically wrong

I don't get it?

**Comment by mikrosk** [comment]
> I don't get it?

Oops, now I get it. :-) I thought that as `GTIA_OFFSET_PRIOR` is meant as an index to the GTIA base as one case see e.g. here: https://github.com/atari800/atari800/blob/a512ff950b61c19feaeffb4af4f79fe9532cc9ff/src/gtia.c#L1336, therefore the code was supposed to compare `byte` to the value stored in that register. But now I see we compare **address** (`addr & 0x1f`) so yes, `GTIA_OFFSET_PRIOR` is the right one.

Thanks for clearing up my doubts!
