### ISSUE TITLE
Broken Keystroke replaying - does not work.

### ISSUE THREAD

**Issue by jhusak** [atari800/atari800#217]
Replaying is broken (MacbookPro M1, OSX Ventura)
Try use Action image cartridge, mount it. Invoke atari800 -cart 'action.car' -record kstrokes; Wait till action editor shows. Press shift-control-m and press F9 to exit.
Then replaying does not work correctly; shows multiple:
adler32 does not match
adler32 does not match
adler32 does not match
adler32 does not match
adler32 does not match
lines.
and finishes way before editor shows. However, If I wait long enough with first keystroke, then the rest seems to work somehow.
Also, playback seems to skip some chars entered.

I wonder, why is this screen chksum adler32 calculated for. It would be sufficient to replay basing on vsync events. If user replays on another settings and apps? So what?

**Comment by mikrosk** [comment]
@jhusak can you please provide the CAR image and some use case so even a person without any prior knowledge can retest your scenario?

**Comment by atarixle** [comment]
Fast typing is not possible in atari800, the emulator eats keystrokes ... no matter what system (Win/Lin/Mac/others).
Today at the Fujiama we found out that replacing while(...) (to check for events in the event-queue in the main loop) with if(...) the fast typing problem seems to be solved. May be this could help.

**Comment by mikrosk** [comment]
@atarixle i presume you were testing / changing code from the master branch? If so, then this is extremely unexpected because I fixed *exactly* this problem with introducing the while cycle - otherwise the key strokes were lost. 

I can check again but I'm fairly sure that I tested both Linux and Windows builds and could not only reproduce the original problem (characters lost) but also the fixed behaviour.

I tested it in Atari Basic. Maybe you have a more sophisticated test case?

**Comment by mikrosk** [comment]
Also, if you were really recompiling for all three platforms can you check whether it was against SDL1.2 or SDL2+libsdl12-compact?

**Comment by atarixle** [comment]
I was fast typing in Turbo-BASIC. When I typed the command "DIR", it reproducible missed the "R" keystroke. When Norman checked out for the problem, he swapped the "while" with "if" and the problem disappeared (in /src/sdl/input.c line 440). BUT now the last-key-buffer magically was larger than one keystroke (obviously the Atari-VM now receives the keystrokes from the host OS' keyboard-buffer). I re-compiled the sources of 5.2.0.

**Comment by joysfera** [comment]
@atarixle if you're going to recompile the source fetch the newest one from github first. This issue (and many others) might have been fixed already.

**Comment by atarixle** [comment]
I will do as soon as I find the time. Fujiama is over so everyday life tasks are back.

**Comment by atarixle** [comment]
sorry for the delay. the freshly pulled github build seems to work fine with fast typing.

**Comment by mikrosk** [comment]
Phew. :) You got me worried for a minute.

Thank you for retesting, you saved me a lot of time today!

Since I had this already open... I tried to reproduce @jhusak's report:

- I downloaded https://www.atarimania.com/utility-atari-400-800-xl-xe-action_s10963.html
- ran latest atari800 with `atari800 -cart ./Action_cart_and_Runtime_disk/Action\ \(OSS\ Type\ B\)\ \(Action\!\ 3.6\).bin -record kstrokes`
- chose OSS one chip 16 KB cartridge
- pressed shift-control-m and F9 to exit
- ran `atari800 -cart ./Action_cart_and_Runtime_disk/Action\ \(OSS\ Type\ B\)\ \(Action\!\ 3.6\).bin -playback kstrokes`
- chose OSS one chip 16 KB cartridge
- **confirmed:** saw the stream of `adler32 does not match` messages
- **not confirmed:** it seemed to me doing its job? It entered the command prompt and exited

@jhusak please retest on master. The messages are still quite annoying and need to be investigated but it's a far less serious issue.

**Comment by mikrosk** [comment]
Closing as no response given and worked for me.
