### ISSUE TITLE
Atari800 and FujiNet-PC

### ISSUE THREAD

**Issue by brad-colbert** [atari800/atari800#226]
Hello Atari800 Development Community!

On behalf of Thom Cherryhomes from the FujiNet project.  In an effort to bring our efforts together, as I believe that the unique strengths and expertise of each group, when combined, will lead to unparalleled productivity, innovation, and success in our endeavors.

We have a version of FujiNet that is intended to be used with emulators:
https://github.com/FujiNetWIFI/fujinet-pc

It builds a stand-alone binary that can accept command frames over UDP, and there is a corresponding bridge for Altirra:
https://github.com/FujiNetWIFI/fujinet-emulator-bridge

Would you like to work with us to try and add support for FujiNet-PC to Atari800?

In case you want to drop by and chat, our discord URL is:
https://discord.gg/2Ce9guX

Sincerely,
-Thom and the Fujinet community

**Comment by mikrosk** [comment]
Hey,

this is a nice setup! I also own the physical device (FujiNet) but never heard of this PC flavour until now.

The thing with Atari800 is that it has been for several years in sort of maintenance mode, i.e. whoever wants to get something fixed / added, it must do it by himself, there are no active developers left.

So if you would like to see something similar in Atari800, come forward with patches, they will get reviewed and included in the main tree. We (I) can provide some support and help but I have no resources to help you with implementation.

**Comment by mozzwald** [comment]
@mikrosk a couple folks (including me) from the Fujinet team have begun looking into adding support for it in atari800. My rough plan is to create a thread that runs [netsio](https://github.com/fujinetwifi/fujinet-emulator-bridge/blob/main/netsio.md) to forward *all* SIO packets to and from FujiNet-PC.

I currently have this thread framework implemented and it is able to negotiate the connection with FujiNet-PC. My next step is to do the command frame implementation and I'm a bit stuck here so I'm asking if you can point me in the right direction. Basically, we need to tell Fujinet-PC that the command line is asserted, send the command frame bytes and then tell it the command line has been deasserted. I have attempted to send a NETSIO_COMMAND_ON from sio.c `SIO_SwitchCommandFrame()` but this function is never called. I added a log print to pia.c:

```static void set_CB2(int value)
{
	/* This code is part of the serial I/O emulation */
	if (PIA_CB2 != value) {
		/* The command line status has changed */
		Log_print("set_CB2: cmd line status changed");
		SIO_SwitchCommandFrame(!value);
	}
	PIA_CB2 = value;
}
```

So, can you tell me where the command line status is actually managed?

Thanks

**Comment by mikrosk** [comment]
@mozzwald nice! I'd recommend to post this kind of stuff to Atari800 mailing list for better visibility. As for your question, embarrassingly I don't know that much about Atari800 internals, I also learn on the go when I need to fix something.

If I were you, I'd start with tracing e.g. ATR loading: that should show you which functions are called and then you can experiment with injecting them with your code.

**Comment by mozzwald** [comment]
Thanks. I've determined there are multiple paths for SIO communication depending if "SIO patch emulation routine" is enabled or not. Now we need to determine which path is better or if should we do both.

**Comment by mozzwald** [comment]
@mikrosk 

I guess now is a good time to show what we have and get some advice on how to proceed. Perhaps we can just reopen this thread and work through it here. This is better for me than the antiquated sourceforge mailing list.

We have implemented the netsio protocol as a pthread. This forwards SIO packets to and from fujinet-pc (usually) running on the same machine. If `-netsio` is added to cli switches, it enables the feature. Upon emulator startup, it waits for fujinet connection before proceeding to emulation. Most of the new code is in netsio.c and the rest in sio.c [GetByte() and PutByte()] and pokey.c. There is much cleanup to be done but I wanted to show what we have working. Only tested on linux which is my main reason for doing this since Altirra already supports Fujinet on Windows.

The current source tree is at my fork in branch [netsio-device-agnostic](https://github.com/mozzwald/atari800/tree/netsio-device-agnostic). 

To test, build the source tree above and add `-netsio` switch to cli arguments. Then, run [fujinet-pc](https://github.com/FujiNetWIFI/fujinet-firmware/releases/tag/nightly_fn_pc_v1.5.0%2Bgit-f86b0baf). When they connect, emulation will begin and boot fujinet config. You can test the network device by running `L`obby from config and run either 5 Card Stud or Fujitzee networked games.

So, my questions for how to proceed are:

1. is this in fact the *official* source for atari800 and not the sourceforge repo?
2. do you want to require a configure switch/cflag to enable netsio at build time?
3. do you have any other concerns / requests / information / advice that would help get this upstream when finished

There is more to be done such as integrating Fujinet Rdevice and Printer emulation, but for now disk and network device are working.

Thanks and looking forward to some advice

**Comment by joysfera** [comment]
> 1. is this in fact the _official_ source for atari800

yes.

> 2. do you want to require a configure switch/cflag to enable netsio at build time?

yes, similar to other special features.

**Comment by mikrosk** [comment]
@mozzwald I'd also recommend to create a PR (it can be still a draft) so you can get comments on your code directly, as you seem to prefer Github's fancy features. :-)
