### ISSUE TITLE
--enable-volonlysound, --enable-seriosound and --enable-consolesound confusion

### ISSUE THREAD

**Issue by mikrosk** [atari800/atari800#229]
For some time I have been quite confused by those three `./configure` parameters.

Vanilla `./configure` generates this output:
```
[...]
    Using volume only sound?..........: 
        (Volume only sound sub-options disabled)
[...]
```
those sub-options are disabled because `--enable-synchronized_sound` is set by default and it conflicts with `--enable-volonlysound`. And indeed, `--disable-synchronized_sound` leads to:
```
[...]
    Using volume only sound?..........: yes
        Using console sound?..........: yes
        Using serial I/O sound?.......: no
[...]
```
This seems to imply that unless `--enable-volonlysound` is set, we can't use those two sub-options. And this is not true at all:
- `--enable-consolesound` is still set by default (generating `CONSOLE_SOUND` in `config.h`) and having an effect when enabled/disabled (key click in BASIC for example)
- `--enable-seriosound` is not set by default (but still being independent from volume only sound) and has no visible/audible effect  (that is except generating `SERIO_SOUND` and some code). I'd assume that when booting from an non-bootable disk (the infamous BOOT ERROR messages) I should hear the classic Atari SIO sound and nope. On the other hand, there is _some_ noise generated when loading a file / ATR regardless of this option.

Now, commit 5cd88a9b mentions:
> Sound can now be generated in sync with the rest of the emulation and not in a
> separate thread.  VOL_ONLY_SOUND is no longer needed.  GTIA and POKEY
> digisounds now work properly.

Uhm, okay. So this leads me to three questions:

- do we need `--enable-volonlysound` at all?
- does it make sense to hide the sub-options?
- is `--enable-seriosound` broken? I.e. should it generate the proper SIO sounds (BOOT ERROR, disk I/O etc) ? If not, does it have any purpose (since it's disabled by default anyway)?

Does someone remember? @kr0tki @pfusik @joysfera ?

**Comment by mikrosk** [comment]
Thanks to my work on #188 I have noticed that the volume only driver (and disabled synchronized sound) is still present on Windows as this backend actively refuses to use SDL audio. Hmm.

**Comment by pfusik** [comment]
Initially Atari800 generated the audio on interrupts. Possibly at a different pace than the emulation of 6502, ANTIC etc. This was acceptable for POKEY chiptunes and fx's, especially in the '90s where we struggled to have 100% Atari speed. But the sampled sounds did not work at all.

Then someone added `VOL_ONLY`, which was a communication from the emulation thread to the "audio" thread of all the "store sample to the POKEY" events, GTIA sound events and serial I/O sounds (the latter two under additional `#define`s), for the "synthesized audio" waveform to be patched. This worked for ports that had good sync of audio and video, but produced horrible sounds on others, to the point that it was better to have no `VOL_ONLY` than hear awful garbled sounds.

"Synchronized sounds" are how Atari800 should really work. The "digitized" and "synthesized" sounds shouldn't really be treated differently and should be generated in the main thread to prevent desync, race conditions etc. The commit you mention is from 2009 and I wasn't aware of it until now. Perhaps some ports had/still have problems with this approach.

Serial I/O sound is for disk read when the SIO patch is disabled. Ideally it should sound same as on the real Atari. I don't know how good it is now, but years ago I could tell the difference. The regular disk transfer is about 19200 (actually a bit different, and dependent on PAL/NTSC) which is not audible to most people, what we hear is the byte rate which is 1/10 of that (1 start bit + 8 bits of data + 1 stop bit), because POKEY is in a mode that synchronizes the counters with the incoming start bit.

**Comment by mikrosk** [comment]
Thanks for the detailed explanation. So to me it looks like `--enable-volonlysound` should be removed and the other two options should be made normal sound (sub-)options.

That brings me to the other  issue, Serial I/O sound. It seems that the switch doesn't have any meaning anymore. After disabling the SIO patch and booting either empty disk image or some DOS, yes, OK, I can hear it clicking but it's anything but the classic 19200  Bd sound and enable/disable of SERIO_SOUND doesn't make any difference.

**Comment by mikrosk** [comment]
After some digging in the past builds I can confidently say that the current state of I/O sounds is definitely not worse. It definitely helps to have the High fidelity POKEY emulation enabled. However it is far, far away from real hardware and, of course, Altirra.

I'm keeping this one open until someone confirms that we can kill the Serial I/O Sound switch (and code) because yes, it doesn't seem to have any effect. Same for the Volume Only switch (i guess this implies that there are no ports not using the synchronized sound). So in effect, only `--enable-consolesound` should be kept.

**Comment by wolfensg** [comment]
Sorry for digging in the closed issues but... I just came across this one. Do I understand correctly (the last comment and the comment) the SERIOSOUND has been removed from master? i.e. all future builds of Atari800 will not have this function?

If yes - that would mean that Atari800 will no longer be able to generate sound when loading data from tapes (.CAS format) as this switch (and the relevant part of the code) is required during the compilation. If the switch is not provided the compiled binary of Atari800 during the load process will have silence when reading the pilot part of the CAS tape image and will only "beep" signaling the read process of the record instead the real sound of the data record being read which is significant step back in the cassette tape emulation.

**Comment by mikrosk** [comment]
@wolfensg are you saying that you had a use case for `--enable-seriosound` ? As mentioned, this switch was disabled by default (and nobody was explicitly enabling it, AFAIK) so I'm wondering whether nobody cared about the scenario you have just described or it was you alone who appreciated this option to be available.

**Comment by wolfensg** [comment]
@mikrosk Yes, this was disabled by default but I intentionally enabled it always during the compilation (especially when applying kr0tki's patches to support liba8cas in atari800 4.2.0 and provide sound for various cassette turbo systems like Turbo 2000, Turbo Blizzard, etc). I haven't compiled atari800 5.2.0 yet but the precompiled binary (i.e. default with seriosound disabled) does not provide serial input audio, i.e. loading from cassette tapes is silent apart from ugly beeps signaling the process of reading a record.

**Comment by wolfensg** [comment]
The difference is:
https://www.youtube.com/watch?v=jLQfGr8qsUI (standard transmission sound - captured from real Atari but atari800 was close enough)
https://www.youtube.com/watch?v=4njUK4GIjNY (Turbo Blizzard)

I'm not sure if applying liba8cas would be possible if the seriosound is removed but probably in both (or at least for standard transmission you'd hear silence and "beep" for each data record being read from .CAS.

[a8-TAPES(FAV).zip](https://github.com/user-attachments/files/17229261/a8-TAPES.FAV.zip)

I guess the integration of liba8cas is out of discussion (it was decided even by kr0tki who (if I remember correctly) maintains liba8cas against including this in atari800) so I included above some .CAS images for tapes in standard transmission.

Steps to reproduce to hear the sound:
1. Compile atari800 from source with --enable-seriosound
2. Configure emulator (provide original ROM files and disable SIO Patch (ENABLE_SIO_PATCH=0)
3. Load .cas (F1 -> Select .CAS file)

Steps to reproduce to hear the silence:
1. Grab any currently build binary (by default it has seriosound disabled)
2. Configure emulator (provide original ROM files and disable SIO Patch (ENABLE_SIO_PATCH=0)
3. Load .cas (F1 -> Select .CAS file)

So.... from what you wrote here already I suspect that chances for keeping the seriosound is close to zero. Thanks in advance for checking anyway.

**Comment by mikrosk** [comment]
We'll see, I'll reopen the issue for now so I don't forget about it.

**Comment by mikrosk** [comment]
I found some time tonight to check it out. Unfortunately, I can't confirm your observation / description.

When I just `./configure` atari800 (i.e. synchronised sound enabled, serial i/o sound disabled), I get the initial cassette beep and then the high-pitch sounds when loading.

When I took 5.2.0 and `./configure --enable-seriosound --disable-synchronized_sound` (the latter is needed to enable the volume only sound and therefore serial i/o sound), the initial cassette beep sounded much worse than I got the exact same high-pitch sounds as before.

Can you please try plain 5.2.0 on your setup, just to be sure that your enhanced sound features do not come solely from liba8cas? Of course, even if they did our problem isn't gone but maybe the libca8cas patch could be extended in such a way that it would reapply the volume only sound code/options and therefore everyone would be happy (assuming that the other two projects also rely on liba8cas patches to Atari800).

Anyway, I would be interested to know why @kr0tki's liba8cas patches are not suitable for Atari800 mainline in the first place.

**Comment by mikrosk** [comment]
Hold on a second. Looking into the a8cas changes of Atari800 has revealed  that the situation is not that bad as I had thought. @kr0tki is a smart guy so while he did use the switch `--enable-seriosound`, his code doesn't require `--disable-synchronized_sound` anymore, therefore it is fully compatible with current code base. The only thing he needs is just to adapt this patch so serial i/o is always enabled (because without his patch serial i/o served no real purpose).

As for the reasons of not including it into Atari800, I found this statement:

```
POKEY serial input/output emulation is slightly broken - the changes related
to tape emulation have caused some disk images to stop functioning. The known
affected disks are all 4 Epyx releases of Lucasilm games. These disks work
correctly only in the stantard Atari800.
```
Hm.

**Comment by wolfensg** [comment]
I can reproduce it quickly with (as an example) unmodified build straight from atari800: https://github.com/atari800/atari800/releases/download/ATARI800_5_2_0/atari800-5.2.0-win32-sdl.zip

When trying to load a CAS file the pilot part of the signal is silent, then I can hear beeps instead of sound of data records being loaded and processed by Pokey.

I haven't tried for some time to compile vanilla atari800 with seriosound enabled so maybe it is something that stopped working a while ago but I'm pretty sure 4.X version did play CAS correctly.

Let me check this and get back to you. I'm also curious now when it stopped working or maybe I just got used to modified atari800 too much.

Anyway removing seriosound from atari800 would probably either require reimplementation for liba8cas or another type of workaround.

**Comment by wolfensg** [comment]
Okay. It looks like I was wrong. Either seriosound stopped working a long while ago OR I just got used to modified atari800 (with liba8cas) and Altirra which both provide proper sound for the cassette loading process.

https://github.com/user-attachments/assets/147dafb1-5c9d-4199-9f75-c0f8e15bf594
https://github.com/user-attachments/assets/0a1fae7a-f4e0-489e-bcf1-7cdb01b8612d

Please find attached comparison of the sound between atari800 4.2.0 (taken straight from the atari800 repo) and atari800 4.2.0 with liba8cas. Sorry for the potato-like quality of the video (used laptop with very low quality screen and in pretty bad lighting conditions - but the sound is more important here ;)

After all it looks like seriosound flag is not the only thing that is causing the proper rendition of the sound as I have tested so far:
atari800 5.2.0, atari800 4.2.0 and atari800 4.0.0 and all three produce silence when loading a CAS file pilot and beeps (high-pitch with constant frequency sound) when loading a data record (4.0.0 actually sounded much worse also)

It seems that I got used to modified atari800 (and Altirra) too much. Sorry for the confusion around this.

**Comment by mikrosk** [comment]
> I will build myslef atari800 5.2.0 with seriosound enabled for comparison and get back to you (probably tomorrow) to confirm if the flag does anything or anyway requires liba8cas to produce the loading sound correctly.

Just don't forget that the flag will activate only with `--disable-synchronized_sound` (which was enabled by default for win32 sdl builds, maybe for this one odd reason?).

Currently (after 5.2.0), win32 builds also use SDL sound API, so the volume only option ("disabled synchronised sound") was not needed anymore.

**Comment by dmsc** [comment]
Hi!

In reality, it is not possible to emulate the real loading sound from a CAS file, as it depends on:
- The POKEY chip used - some had more crosstalk than others,
- The tape player, same as before, some tape players mixed L and R channels, and the pitch changed slightly because deviations in the play speed.
- The actual recording. Some tapes had the load sounds in only one channel, others had the sounds in both channels.

Atari800 emulates the "ideal" case, with no cross-talks, a perfect channel separation and a perfect tape speed, so it sounds "plain" in comparison with real hardware.

Altirra emulates more of the no-linearity and imperfections of the audio path, so it sounds "more real".

My own Atari 800XL has a bad POKEY chip, with so much cross-talk that you can't silence SIO sounds, so I can't really compare :P

**Comment by phaeron1024** [comment]
The reason why the Lucasfilm-Epyx loader breaks with the a8cas patch is subtle and has to do with its use of the serial output complete IRQ. The a8cas patch is actually more accurate in not turning off the serial output complete IRQ immediately after STA SEROUT, but the serial timing is not precise enough. The loader relies on the next serial tick arriving soon enough after SEROUT is written so that the 6502 isn't fast enough to re-enter the IRQ handler and notice the complete IRQ still active in IRQST. With the a8cas patch, it re-enters the IRQ handler and raises the SIO command line too early, resulting in the SIO code complaining (Command frame 01 unfinished).

As for the cassette sound, besides the tape audio, there is also the same asynchronous receive sound issue as with disk reads. The difference is that while the bit tone is inaudible for disk reads, it is well within audible range for tape reads, so POKEY's output has a 30Hz component as well as a 600Hz component.

Note that Altirra does not emulate crosstalk for serial input, only serial output. The mode where the data track can be heard isn't a crosstalk mode, it's simply assuming a mono tape where the data and audio tracks are the same. For a CAS file, this involves resynthesizing the FSK tones from the data.

**Comment by wolfensg** [comment]
@mikrosk 
I did the test with two builds with seriosound flag AND separate one with both seriosound and as per your request disable-synchronized_sound (I did it this way as I remember only ever building atari800 with seriosound). As target platform I used Linux (Ubuntu based 24.04 OS) + SDL.

In both cases on vanilla atari800 5.2.0 source code taken straight from the github repo I did not get the proper loading sound (only silence+beeps) (without disable-synchronized_sound it was even sounding way worse)

It looks like after all I was mistaken and the "real" loading sound is exclusive to atari800 WITH liba8cas only (or Altirra ;)

So I guess the last thing up to the discussion is if the seriosound could be kept for the sake of compatibility with liba8cas or dropped (or an alternative can be found)?

**Comment by mikrosk** [comment]
> So I guess the last thing up to the discussion is if the seriosound could be kept for the sake of compatibility with liba8cas or dropped (or an alternative can be found)?

As mentioned above, there isn't wasn't any "vanilla" serio sound in Atari800. You needed the volume only sound to make it work at least _somehow_. So liba8cas will do the heavy lifting for you even with current master. Its author will have to slightly modify his patch, that's all.

So I'm closing this one however I'm going to create a separate issue about liba8cas integration.
