### ISSUE TITLE
Error in DOC/INSTALL about -configure

### ISSUE THREAD

**Issue by mobluse** [atari800/atari800#74]
This is wrong (in my case):

> The first time you run the emulator you will be prompted for the
> location of the ROMs and various other defaults. If you want to
> change any of these in the future simply start the emulator with
> the "-configure" command line option. 

I was not prompted. The only way to start it was to start in the `xf25` directory. Then it filled in some entries in `.atari800.cfg` when I saved configuration from within the emulator. Then I edited the file to make those path names absolute. Now I can start `atari800` everywhere.

It would be useful with an example `.atari800.cfg` file with all ROM entries filled in that are in `xf25`.

**Comment by mikrosk** [comment]
Good catch, this is should have been removed a long time ago (since 2005 or so). However your report has pointed me to the real problem here and that is that we really take "." as current directory when searching for ROMs. So I have changed it into absolute path instead so now you can start `atari800` from `xf25` directory and absolute paths to the ROMs will be saved.
